In [1]:
import numpy as np
import matplotlib.pylab as plt
import pandas as pd
%matplotlib inline

In [2]:
design_dataset=pd.read_csv('design.csv')
yarn_consumption_dataset=pd.read_csv('yarn-consumption.csv')
results_dataset=pd.read_csv('results.csv')

In [3]:
design_dataset.head()

  DesignId  Knit Per cm  Stretch  Courses    PRL    PRW  NeedleSetup  NoBands
0   D00001           38     0.60    112.0   29.0  170.0          192       16
1   D00002           38     0.60    240.0   63.0  170.0          192       16
2   D00003           40     0.60    120.0   30.0  230.0          256       12
3   D00004           38     0.55    456.0  120.0  230.0          256       12
4   D00005           38     0.70     23.0   92.0   60.0          192       51

In [4]:
yarn_consumption_dataset.head()

  DesignId YarnType  Count   MperRepeat  Percentage
0   D00005    Yarn1  310.0   379.799988   28.465035
1   D00005    Yarn6  235.0    30.309999    1.722062
2   D00005    Yarn7  235.0   290.299988   16.493391
3   D00005    Yarn9   44.0  1741.000000   18.520237
4   D00005   Yarn10   44.0   442.149994    4.703459

In [5]:
results_dataset.head()

  DesignId   PRL    PRW  Stretch   FRJ  FRP  FRL MC type
0   D00002  55.0  120.0      0.6  1065  400  160      JQ
1   D00002  63.0  115.0      0.6  1125  330  160      JQ
2   D00002  51.0  125.0      0.6  1000  420  160      JQ
3   D00002  50.0  120.0      0.6  1080  400  160      JQ
4   D00002  55.0  120.0      0.6  1020  435  160      JQ

In [6]:
new_data_1=pd.merge(design_dataset, yarn_consumption_dataset, on='DesignId')

In [7]:
new_data_1.head()

,DesignId,Knit Per cm,Stretch,Courses,PRL,PRW,NeedleSetup,NoBands,YarnType,Count,MperRepeat,Percentage
0,D00005,38,0.7,23.0,92.0,60.0,192,51,Yarn1,310.0,379.799988,28.465035
1,D00005,38,0.7,23.0,92.0,60.0,192,51,Yarn6,235.0,30.309999,1.722062
2,D00005,38,0.7,23.0,92.0,60.0,192,51,Yarn7,235.0,290.299988,16.493391
3,D00005,38,0.7,23.0,92.0,60.0,192,51,Yarn9,44.0,1741.000000,18.520237
4,D00005,38,0.7,23.0,92.0,60.0,192,51,Yarn10,44.0,442.149994,4.703459

In [8]:
new_data_1.replace(0, np.nan, inplace= True)
new_data_1.replace(np.nan, np.round(new_data_1.mean(), decimals=1), inplace= True)

In [9]:
# new_data_1.to_csv('new_data_1.csv', sep='\t')

In [10]:
final_dataset=pd.merge(new_data_1, results_dataset, on=['DesignId','PRL','PRW','Stretch'])

In [11]:
final_dataset.head()

,DesignId,Knit Per cm,Stretch,Courses,PRL,PRW,NeedleSetup,NoBands,YarnType,Count,MperRepeat,Percentage,FRJ,FRP,FRL,MC type
0,D00126,38,0.7,304.0,80.0,30.0,192,60,Yarn1,312.0,98.26,9.12,1255,300,190,JL
1,D00126,38,0.7,304.0,80.0,30.0,192,60,Yarn7,470.0,308.70,43.17,1255,300,190,JL
2,D00126,38,0.7,304.0,80.0,30.0,192,60,Yarn14,156.0,126.60,5.88,1255,300,190,JL
3,D00126,38,0.7,304.0,80.0,30.0,192,60,Yarn15,78.0,100.50,2.33,1255,300,190,JL
4,D00126,38,0.7,304.0,80.0,30.0,192,60,Yarn19,44.0,617.80,8.09,1255,300,190,JL

In [12]:
final_dataset.to_csv('final_dataset.csv')

In [13]:
final_dataset.describe()

,Knit Per cm,Stretch,Courses,PRL,PRW,NeedleSetup,NoBands,Count,MperRepeat,Percentage,FRJ,FRP,FRL
count,317.000000,317.000000,317.000000,317.000000,317.000000,317.000000,317.000000,317.000000,317.000000,317.000000,317.000000,317.000000,317.000000
mean,38.662461,0.653312,322.687697,84.053628,134.719243,213.324921,44.119874,220.607571,396.863659,11.126467,1164.779180,298.974763,197.570978
std,2.163333,0.080525,152.333475,39.513501,88.694398,31.194142,43.932033,283.978798,610.742792,11.854364,75.037639,110.691752,22.224377
min,35.000000,0.600000,64.000000,16.000000,11.000000,168.000000,2.000000,33.000000,3.200000,0.010000,1010.000000,0.000000,160.000000
25%,38.000000,0.600000,264.000000,70.000000,26.000000,192.000000,12.000000,44.000000,20.180000,1.010000,1120.000000,300.000000,180.000000
50%,40.000000,0.600000,360.000000,90.000000,170.000000,192.000000,16.000000,110.000000,117.500000,8.110000,1175.000000,330.000000,200.000000
75%,40.000000,0.700000,440.000000,115.000000,230.000000,256.000000,72.000000,312.000000,590.500000,17.240000,1220.000000,360.000000,220.000000
max,42.000000,0.800000,552.000000,138.000000,230.000000,256.000000,128.000000,1250.000000,3042.000000,46.850000,1265.000000,420.000000,240.000000